# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.x'
  targetRuntime: 'linux-x64'

steps:
- task: UseDotNet@2
  inputs:
    version: $(dotNetVersion)
    includePreviewVersions: true
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET 6 Application'

# Publish it as .NET 6 self-contained application for linux runtime
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish src/MensSectionAPI/MensSectionAPI.csproj /p:PublishProfile=IISProfile.pubxml'
  inputs:
    command: publish
    publishWebProjects: false
    arguments: 'src/MensSectionAPI/MensSectionAPI.csproj --framework $(dotNetFramework) /p:PublishProfile=IISProfile.pubxml /p:password=passiv'
    zipAfterPublish: true
